### ISSUE TITLE
JVM GC metrics in jmx-1.yaml are named wrong

### ISSUE THREAD

**Issue by timw** [DataDog/jmxfetch#106] opened 2016-09-07 20:10 UTC
The garbage collector metrics auto-added by jmxfetch in `jmx-1.yaml` are incorrectly labeled with specific GC types that are not universally used.

e.g. the `CollectionCount` for all collector types is named `jvm.gc.cms.count`, even though it is the metric name for counts for all collector types (of which there are many).
Similarly `CollectionTime` is labeled `jvm.gc.parnew.time` for all collectors.

Obviously this is just naming, and you can functionally use the metrics, but it's a bit (facepalm) for a Java engineer to see.

These metrics would more appropriately be named `jvm.gc.count` and `jvm.gc.time` - the existing tags created for the `name` part of the bean name allow the different collectors to be identified.

**Comment by michaelajr** [comment] 2016-10-14 09:50
Yes. This was very confusing. Please rename these as described in the OP.

**Comment by michaelajr** [comment] 2016-10-14 10:00
Also wondering if the same approach might work for HEAP and NON-HEAP. Using tags for the different parts of the heap, e.g., eden, survivor, tenured. This would really be nice to have OOTB.

**Comment by michaelajr** [comment] 2016-10-14 11:33
`  conf:
      - include:
            domain: java.lang
            type: MemoryPool
            attribute:
                CollectionUsage.used:
                    alias: jvm.memory_pool.used
                    metric_type: gauge
                CollectionUsage.max:
                    alias: jvm.memory_pool.max
                    metric_type: gauge
                CollectionUsage.init:
                    alias: jvm.memory_pool.init
                    metric_type: gauge
                CollectionUsage.committed:
                    alias: jvm.memory_pool.committed
                    metric_type: gauge
      - include:
            domain: java.lang
            type: GarbageCollector
            attribute:
                CollectionCount:
                    alias: jvm.gc.count
                    metric_type: gauge
                CollectionTime:
                    alias: jvm.gc.time
                    metric_type: gauge
`

**Comment by michaelajr** [comment] 2016-10-14 11:34
```conf:
      - include:
            domain: java.lang
            type: MemoryPool
            attribute:
                CollectionUsage.used:
                    alias: jvm.memory_pool.used
                    metric_type: gauge
                CollectionUsage.max:
                    alias: jvm.memory_pool.max
                    metric_type: gauge
                CollectionUsage.init:
                    alias: jvm.memory_pool.init
                    metric_type: gauge
                CollectionUsage.committed:
                    alias: jvm.memory_pool.committed
                    metric_type: gauge
      - include:
            domain: java.lang
            type: GarbageCollector
            attribute:
                CollectionCount:
                    alias: jvm.gc.count
                    metric_type: gauge
                CollectionTime:
                    alias: jvm.gc.time
                    metric_type: gauge
```

**Comment by michaelajr** [comment] 2016-10-14 11:44
<img width="1008" alt="screen shot 2016-10-14 at 7 18 20 am" src="https://cloud.githubusercontent.com/assets/658602/19386392/eede1940-91e1-11e6-98ef-3cb2ed3dadd6.png">

<img width="1244" alt="screen shot 2016-10-14 at 7 27 26 am" src="https://cloud.githubusercontent.com/assets/658602/19386399/fe46dc14-91e1-11e6-8fb1-528c89631ce5.png">

**Comment by yannmh** [comment] 2016-10-14 13:56
Thanks for your feedback @timw, @michaelajr.

We are actually aware of the issue: unfortunately, the name of the metric cannot be "changed" without breaking the backward compatibility (when these metrics are used in monitors, dashboards...). 
Still, we can keep the existing metrics and add them again with different names: it would basically be duplicate of the culprit metrics, but with the correct names. 
Would this option work for you?

**Comment by michaelajr** [comment] 2016-10-14 18:08
Hate to leave confusing names in there. Confusion will be compounded by adding the new names. But I understand the situation.

Also, my `attribute` names in the previous post were wrong. If you plan on adding the `memory_pool` metrics as defaults to the JMX collector, use these instead:

```        - include:
              domain: java.lang
              type: MemoryPool
              attribute:
                  Usage.used:
                      alias: jvm.memory_pool.used
                      metric_type: gauge
                  Usage.max:
                      alias: jvm.memory_pool.max
                      metric_type: gauge
                  Usage.init:
                      alias: jvm.memory_pool.init
                      metric_type: gauge
                  Usage.committed:
                      alias: jvm.memory_pool.committed
                      metric_type: gauge```

**Comment by dgolombek** [comment] 2017-02-13 17:38
Here's another vote for new names. Why not add the new names, then slowly deprecate the old names over the next year (or whatever timeframe is appropriate)?

I'll also note that this does drop differentiation between the different pools, which can be pretty important at times. Something like https://gist.github.com/infynyxx/745c11089d4f2094ad81 would include full detailed information, but at the cost of using a lot more of the 350 maximum entries.

**Comment by jhmartin** [comment] 2017-02-16 00:41
Why are count and time guages vs counters, as they are steadily increasing values?

**Comment by dgolombek** [comment] 2017-02-16 02:59
Count and time get reset to 0 every time the JVM restarts

**Comment by jhmartin** [comment] 2017-02-16 03:38
@dgolombek thats equivalent to a router packet counter, which is the textbook definition of a 'counter'. A guage is more like the current amount of memory used, vs a counter which is the total time spent in GC.

**Comment by gplasky** [comment] 2017-10-11 17:42
At the very least, please update the documentation to this effect:

https://docs.datadoghq.com/integrations/java/

The description for `jvm.gc.cms.count`is also missing the unit from the description ("shown as ???"

**Comment by arbll** [comment] 2019-07-17 15:52
Hey there,

New names for those metrics are available since https://github.com/DataDog/jmxfetch/pull/197. The rename is behind a config option to avoid breaking compatibility.

Here is an example on how to set it up:
https://github.com/DataDog/datadog-agent/blob/31f494f27ee3301428bb77da6f99d32855db82a8/cmd/agent/dist/conf.d/jmx.d/conf.yaml.example#L8-L13

I'll close this issue, feel free to re-open if I missed something.

**Closed by arbll** 2019-07-17 15:52 UTC
